version: '3.8'

services:
  fastapi-app:
    build: ./app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - keycloak
    environment:
      MONGODB_URI: mongodb://mongodb:27017/mydatabase
      MONGODB_DB_NAME: pastec
      KEYCLOAK_SERVER_URL: http://localhost:8080
      KEYCLOAK_INTERNAL_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: pastec
      KEYCLOAK_CLIENT_ID: pastec_server
      KEYCLOAK_CLIENT_SECRET: dsaImyh0BaQyMiLcaGwhN5ZidUqLz3Lj 
      KEYCLOAK_ADMIN_CLIENT_SECRET: HWQWR8j2bOoaDDsYk0uboQYpF19Wgt96

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "8080:8080"

volumes:
  mongo_data:
  keycloak_data:

