version: '3.8'

services:
  fastapi-app:
    container_name: fastapi 
    build: ./app
    working_dir: /app
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mongodb
      - keycloak
    environment:
      DEBUG: 1
      MONGODB_URI: mongodb://mongodb:27017/pastec_db
      MONGODB_DB_NAME: pastec_db
      KEYCLOAK_SERVER_URL: http://localhost:8080
      KEYCLOAK_INTERNAL_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: pastec
      KEYCLOAK_CLIENT_ID: pastec_server
      KEYCLOAK_CLIENT_ID_NUM: 367abfaa-b91c-44d9-9b39-a87bb05e03ab
      KEYCLOAK_CLIENT_SECRET: dsaImyh0BaQyMiLcaGwhN5ZidUqLz3Lj 
      KEYCLOAK_ADMIN_CLIENT_SECRET: HWQWR8j2bOoaDDsYk0uboQYpF19Wgt96
    volumes:
      - ./app:/app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: pastec_db
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  postgres:
    image: postgres:13
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command:
      - start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend-network
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import

volumes:
  mongo_data:
  postgres_data:

networks:
  backend-network:
    driver: bridge

